DROP TABLE IF EXISTS Borrows;
DROP TABLE IF EXISTS cat_book_table;
DROP TABLE IF EXISTS author_book_table;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Members;

